- name: Create Authelia Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ authelia_data_directory }}"

- name: Authelia Config File
  template:
    src: authelia/configuration.yml
    dest: "{{ authelia_data_directory }}/configuration.yml"

- name: Authelia Docker Container
  docker_container:
    name: authelia
    image: authelia/authelia
    pull: true
    volumes:
      - "{{ authelia_data_directory }}:/var/lib/authelia"
      - "{{ authelia_data_directory }}/configuration.yml:/etc/authelia/configuration.yml:ro"
    ports:
      - "{{ authelia_port }}:9091"
    env:
      TZ: "{{ ansible_nas_timezone }}"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.backend: "authelia"
      traefik.frontend.rule: "Host:{{ authelia_subdomain }}.{{ ansible_nas_domain }}"
      traefik.enable: "true"
      traefik.port: "9091"
