- name: Create Calibre Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ calibre_data_directory }}/config"

- name: Calibre Docker Container
  docker_container:
    name: calibre
    image: linuxserver/calibre-web:latest
    pull: true
    volumes:
      - "{{ calibre_data_directory }}/config:/config"
      - "{{ calibre_books_root }}:/books"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ calibre_user_id }}"
      PGID: "{{ calibre_group_id }}"
      DOCKER_MODS: "{{ calibre_ebook_conversion }}"
    ports:
      - "{{ calibre_port }}:8083"
    restart_policy: unless-stopped
    labels:
      traefik.backend: "calibre"
      traefik.frontend.rule: "Host:{{ calibre_subdomain }}.{{ ansible_nas_domain }}"
      traefik.enable: "{{ calibre_available_externally }}"
      traefik.port: "8083"
      traefik.frontend.auth.forward.address: "{{ omit if authelia_enabled != true or 'http://localhost:' + authelia_port + '/api/verify?rd=https://' + authelia_subdomain + '.' + ansible_nas_domain + '/' }}"
      traefik.frontend.auth.forward.trustForwardHeader: "{{ omit if authelia_enabled != true or 'true' }}"
      traefik.frontend.auth.forward.authResponseHeaders: "{{ omit if authelia_enabled != true or 'Remote-User,Remote-Groups' }}"

    memory: 1g