---
- name: Create Duplicati Directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ duplicati_data_directory }}"

- name: Dupicati Docker Container
  docker_container:
    name: duplicati
    image: linuxserver/duplicati
    pull: true
    ports:
      - "{{ duplicati_port }}:8200"
    volumes:
      - "{{ duplicati_data_directory }}:/config:rw"
      - "{{ samba_shares_root }}:/source/shares:ro"
      - "{{ docker_home }}:/source/docker:ro"
      - "/etc/timezone:/etc/timezone:ro"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.backend: "duplicati"
      traefik.frontend.rule: "Host:{{ duplicati_subdomain }}.{{ ansible_nas_domain }}"
      traefik.enable: "{{ duplicati_available_externally }}"
      traefik.port: "8200"
      {% if authelia_enabled %}
      traefik.frontend.auth.forward.address: "http://localhost:{{ authelia_port }}/api/verify?rd=https://{{ authelia_subdomain }}.{{ ansible_nas_domain }}/"
      traefik.frontend.auth.forward.trustForwardHeader: "true"
      traefik.frontend.auth.forward.authResponseHeaders: "Remote-User,Remote-Groups"
      {% endif %}
