- name: Create Home Assistant Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ homeassistant_data_directory }}/config"

- name: Home Assistant Docker Container
  docker_container:
    name: homeassistant
    image: homeassistant/home-assistant
    pull: true
    volumes:
      - "{{ homeassistant_data_directory }}/config:/config:rw"
    network_mode: host
    restart_policy: unless-stopped
    env:
      TZ: "{{ ansible_nas_timezone }}"
    labels:
      traefik.backend: "homeassistant"
      traefik.frontend.rule: "Host:{{ homeassistant_subdomain }}.{{ ansible_nas_domain }}"
      traefik.enable: "{{ homeassistant_available_externally }}"
      traefik.port: "8123"
      traefik.frontend.auth.forward.address: "{{ omit if authelia_enabled != 'true' else 'http://localhost:' + authelia_port + '/api/verify?rd=https://' + authelia_subdomain + '.' + ansible_nas_domain + '/' }}"
      traefik.frontend.auth.forward.trustForwardHeader: "{{ omit if authelia_enabled != 'true' else 'true' }}"
      traefik.frontend.auth.forward.authResponseHeaders: "{{ omit if authelia_enabled != 'true' else 'Remote-User,Remote-Groups' }}"
      traefik.frontend.headers.SSLRedirect: "true"
    memory: 1g
