---
- name: Create Homebridge Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ homebridge_config_directory }}"

- name: Homebridge Docker Container
  docker_container:
    name: homebridge
    image: oznu/homebridge
    pull: true
    volumes:
      - "{{ homebridge_config_directory }}:/homebridge"
    network_mode: host
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PGID: "{{ homebridge_group_id }}"
      PUID: "{{ homebridge_user_id }}"
      HOMEBRIDGE_CONFIG_UI: "1"
      HOMEBRIDGE_CONFIG_UI_PORT: "{{ homebridge_port }}"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.backend: "homebridge"
      traefik.frontend.rule: "Host:{{ homebridge_subdomain }}.{{ ansible_nas_domain }}"
      traefik.enable: "{{ homebridge_available_externally }}"
      traefik.port: "8087"
      {% if authelia_enabled %}
      traefik.frontend.auth.forward.address: "http://localhost:{{ authelia_port }}/api/verify?rd=https://{{ authelia_subdomain }}.{{ ansible_nas_domain }}/"
      traefik.frontend.auth.forward.trustForwardHeader: "true"
      traefik.frontend.auth.forward.authResponseHeaders: "Remote-User,Remote-Groups"
      {% endif %}
