
---
- name: Create Organizr Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ organizr_data_directory }}"

- name: Create Organizr container
  docker_container:
    name: organizr
    image: organizrtools/organizr-v2:latest
    pull: true
    volumes:
      - "{{ organizr_data_directory }}:/config:rw"
    env:
      PUID: "{{ organizr_user_id }}"
      PGID: "{{ organizr_group_id }}"
      TZ: "{{ ansible_nas_timezone }}"
    ports:
      - "{{ organizr_port_http }}:80"
      - "{{ organizr_port_https }}:443"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.backend: "organizr"
      traefik.frontend.rule: "Host:{{ organizr_subdomain }}.{{ ansible_nas_domain }}"
      traefik.enable: "{{ organizr_available_externally }}"
      traefik.port: "80"
      traefik.frontend.auth.forward.address: "{{ omit if authelia_enabled != 'true' else 'http://localhost:' + authelia_port + '/api/verify?rd=https://' + authelia_subdomain + '.' + ansible_nas_domain + '/' }}"
      traefik.frontend.auth.forward.trustForwardHeader: "{{ omit if authelia_enabled != 'true' else 'true' }}"
      traefik.frontend.auth.forward.authResponseHeaders: "{{ omit if authelia_enabled != 'true' else 'Remote-User,Remote-Groups' }}"
