---
- name: Create Portainer Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ portainer_data_directory }}"

- name: Portainer Docker Container
  docker_container:
    name: portainer
    command: "{{ omit if authelia_enabled != true or '--no-auth' }}"
    image: portainer/portainer
    pull: true
    volumes:
      - "{{ portainer_data_directory }}:/data:rw"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/etc/timezone:/etc/timezone:ro"
    ports:
      - "{{ portainer_port }}:9000"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.backend: "portainer"
      traefik.frontend.rule: "Host:{{ portainer_subdomain }}.{{ ansible_nas_domain }}"
      traefik.enable: "{{ portainer_available_externally }}"
      traefik.port: "9000"
      traefik.frontend.auth.forward.address: "{{ omit if authelia_enabled != true or 'http://localhost:' + authelia_port + '/api/verify?rd=https://' + authelia_subdomain + '.' + ansible_nas_domain + '/' }}"
      traefik.frontend.auth.forward.trustForwardHeader: "{{ omit if authelia_enabled != true or 'true' }}"
      traefik.frontend.auth.forward.authResponseHeaders: "{{ omit if authelia_enabled != true or 'Remote-User,Remote-Groups' }}"
