---
- name: Create Transmission Directories
  file:
    path: "{{ item }}"
    state: directory
    # mode: 0755
  with_items:
    - "{{ transmission_config_directory }}"
    - "{{ transmission_download_directory }}"
    - "{{ transmission_watch_directory }}"

- name: Transmission Docker Container
  docker_container:
    name: transmission
    image: linuxserver/transmission
    pull: true
    volumes:
      - "{{ transmission_config_directory }}:/config:rw"
      - "{{ transmission_download_directory }}:/downloads:rw"
      - "{{ transmission_watch_directory }}:/watch:rw"
    ports:
      - "{{ transmission_webui_port }}:9091"
      - "{{ transmission_external_port }}:51413"
      - "{{ transmission_external_port }}:51413/udp"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ transmission_user_id }}"
      PGID: "{{ transmission_group_id }}"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.backend: "transmission"
      traefik.frontend.rule: "Host:{{ transmission_subdomain }}.{{ ansible_nas_domain }}"
      traefik.enable: "{{ transmission_available_externally }}"
      traefik.port: "9091"
      traefik.frontend.auth.forward.address: "{{ omit if authelia_enabled != 'true' else 'http://localhost:' + authelia_port + '/api/verify?rd=https://' + authelia_subdomain + '.' + ansible_nas_domain + '/' }}"
      traefik.frontend.auth.forward.trustForwardHeader: "{{ omit if authelia_enabled != 'true' else 'true' }}"
      traefik.frontend.auth.forward.authResponseHeaders: "{{ omit if authelia_enabled != 'true' else 'Remote-User,Remote-Groups' }}"
