---
- name: Create uTorrent Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ utorrent_config_directory }}"
    - "{{ utorrent_download_directory }}"

- name: uTorrent Docker Container
  docker_container:
    name: utorrent
    image: ekho/utorrent:latest
    pull: true
    volumes:
      - "{{ utorrent_download_directory }}:/data:rw"
      - "{{ utorrent_config_directory }}:/utorrent/settings:rw"
      - "{{ torrents_root }}:/utorrent/torrents:rw"
    ports:
      - "{{ utorrent_port_http }}:8080"
      - "{{ utorrent_port_bt }}:6881"
      - "{{ utorrent_port_bt }}:6881/udp"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      UID: "{{ utorrent_user_id }}"
      GID: "{{ utorrent_group_id }}"
      webui: "ng"
      dir_active: "/data/.incomplete"
      dir_completed: "/data"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.backend: "utorrent"
      traefik.frontend.rule: "Host:{{ utorrent_subdomain }}.{{ ansible_nas_domain }}"
      traefik.enable: "{{ utorrent_available_externally }}"
      traefik.port: "8080"
      traefik.frontend.auth.forward.address: "{{ omit if authelia_enabled != true or 'http://localhost:' + authelia_port + '/api/verify?rd=https://' + authelia_subdomain + '.' + ansible_nas_domain + '/' }}"
      traefik.frontend.auth.forward.trustForwardHeader: "{{ omit if authelia_enabled != true or 'true' }}"
      traefik.frontend.auth.forward.authResponseHeaders: "{{ omit if authelia_enabled != true or 'Remote-User,Remote-Groups' }}"
