---
- name: Create ZNC Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ znc_data_directory }}"

- name: ZNC
  docker_container:
    name: znc
    image: znc
    pull: true
    volumes:
      - "{{ znc_data_directory }}:/znc-data:rw"
      - "/etc/timezone:/etc/timezone:ro"
    ports:
      - "{{ znc_port }}:6677"
    env:
      PUID: "{{ znc_user_id }}"
      PGID: "{{ znc_group_id }}"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.backend: "znc"
      traefik.frontend.rule: "Host:{{ znc_subdomain }}.{{ ansible_nas_domain }}"
      traefik.enable: "{{ znc_available_externally }}"
      traefik.port: "6677"
      traefik.frontend.auth.forward.address: "{{ omit if authelia_enabled != 'true' else 'http://localhost:' + authelia_port + '/api/verify?rd=https://' + authelia_subdomain + '.' + ansible_nas_domain + '/' }}"
      traefik.frontend.auth.forward.trustForwardHeader: "{{ omit if authelia_enabled != 'true' else 'true' }}"
      traefik.frontend.auth.forward.authResponseHeaders: "{{ omit if authelia_enabled != 'true' else 'Remote-User,Remote-Groups' }}"